package intel

import (
	"fmt"
	"os"
	"strings"
)

// ToMarkdown renders the Index as a markdown document suitable for
// dropping into .claude/context.md so Claude Code auto-loads it.
func ToMarkdown(idx *Index) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Project Context (auto-generated by styx intel)\n\n")
	fmt.Fprintf(&b, "**Project:** %s", idx.Project)
	if idx.Language != "" {
		fmt.Fprintf(&b, " (%s)", idx.Language)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "**Refreshed:** %s (HEAD %s)\n", idx.BuiltAt.Format("2006-01-02 15:04 UTC"), idx.GitHead)
	b.WriteString("\n")

	if c := idx.Conventions; c.TestFramework != "" || c.TypeSystem != "" || c.Naming != "" || c.Imports != "" || c.ErrorHandling != "" {
		b.WriteString("## Conventions\n")
		if c.TestFramework != "" {
			fmt.Fprintf(&b, "- Tests: %s\n", c.TestFramework)
		}
		if c.TypeSystem != "" {
			fmt.Fprintf(&b, "- Type system: %s\n", c.TypeSystem)
		}
		if c.Imports != "" {
			fmt.Fprintf(&b, "- Imports: %s\n", c.Imports)
		}
		if c.Naming != "" {
			fmt.Fprintf(&b, "- Naming: %s\n", c.Naming)
		}
		if c.ErrorHandling != "" {
			fmt.Fprintf(&b, "- Error handling: %s\n", c.ErrorHandling)
		}
		b.WriteString("\n")
	}

	if len(idx.Modules) > 0 {
		b.WriteString("## Module map\n")
		b.WriteString("| Module | Purpose | Entry points |\n")
		b.WriteString("|---|---|---|\n")
		for _, m := range idx.Modules {
			entries := strings.Join(m.EntryPoints, ", ")
			purpose := strings.ReplaceAll(m.Purpose, "\n", " ")
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", m.Path, purpose, entries)
		}
		b.WriteString("\n")
	}

	if len(idx.KeySymbols) > 0 {
		b.WriteString("## Key symbols\n")
		for _, s := range idx.KeySymbols {
			fmt.Fprintf(&b, "- `%s` (%s) — %s\n", s.Name, s.File, s.Why)
		}
		b.WriteString("\n")
	}

	if len(idx.RecentCommits) > 0 {
		b.WriteString("## Recent activity\n")
		for _, c := range idx.RecentCommits {
			fmt.Fprintf(&b, "- %s %s\n", c.SHA, c.Subject)
		}
		b.WriteString("\n")
	}

	if len(idx.OpenTodos) > 0 {
		b.WriteString("## Open TODOs\n")
		for _, td := range idx.OpenTodos {
			fmt.Fprintf(&b, "- %s — %s\n", td.File, td.Text)
		}
		b.WriteString("\n")
	}

	if len(idx.ExternalDeps.Key) > 0 {
		b.WriteString("## External deps\n")
		fmt.Fprintf(&b, "- Key: %s\n", strings.Join(idx.ExternalDeps.Key, ", "))
		if len(idx.ExternalDeps.VersionPinsLikelyIntent) > 0 {
			fmt.Fprintf(&b, "- Likely-intentional pins: %s\n", strings.Join(idx.ExternalDeps.VersionPinsLikelyIntent, ", "))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// WriteContextMD writes the rendered markdown to <project>/.claude/context.md
// atomically. If a non-styx-authored .claude/context.md already exists, the new
// content is written to .claude/context.styx.md instead and the canonical file
// is amended (idempotently) with an @import line so Claude Code loads both.
func WriteContextMD(projectPath, markdown string) (string, error) {
	dir := projectPath + "/.claude"
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	const marker = "<!-- generated by styx intel -->"
	body := marker + "\n" + markdown
	canonical := dir + "/context.md"
	existingBytes, err := os.ReadFile(canonical)
	existing := string(existingBytes)
	if err == nil && !strings.Contains(existing, marker) {
		// User-authored — write to context.styx.md and ensure canonical @imports it.
		styxPath := dir + "/context.styx.md"
		if err := atomicWriteFile(styxPath, body); err != nil {
			return "", err
		}
		importLine := "<!-- styx: -->\n@import context.styx.md"
		if !strings.Contains(existing, "@import context.styx.md") {
			if err := atomicWriteFile(canonical, existing+"\n"+importLine+"\n"); err != nil {
				return "", err
			}
		}
		return styxPath, nil
	}
	if err := atomicWriteFile(canonical, body); err != nil {
		return "", err
	}
	return canonical, nil
}

func atomicWriteFile(p, content string) error {
	tmp := p + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, p)
}
